### ISSUE TITLE
Gulp not working

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#19]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b2, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in: npm install --global gulp-cli
Result:
c:\xampplite\ds-plugins\ds-cli\platform\win32\npm\gulp -> c:\xampplite\ds-plugins\ds-cli\platform\win32\npm\node_modules\gulp-cli\bin\gulp.js
gulp-cli@2.0.1
updated 1 package in 69.993s
(Found node_modules folder created in site root)
4. Type in:  npm install --save-dev gulp@next
Result:
npm WARN www.example.dev.cc@1.0.0 No repository field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"ia32"})
gulp@4.0.0
updated 1 package and audited 5472 packages in 76.231s
found 0 vulnerabilities
5. Type in: gulp or gulp --help

#### RESULT: 
bash: gulp: command not found

#### EXPECTED RESULT: 
Run tasks

Operating System: Win7 64b

**Comment by GreggFranklin** [comment]
Issue resolved
