### ISSUE TITLE
Grunt not working

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#20]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b2, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in:  npm install -g grunt-cli
Result:
c:\xampplite\ds-plugins\ds-cli\platform\win32\npm\grunt -> c:\xampplite\ds-plugins\ds-cli\platform\win32\npm\node_modules\grunt-cli\bin\grunt
grunt-cli@1.3.1
updated 1 package in 22.621s
4. Type in: npm install grunt --save-dev
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN www.example2.dev.cc@1.0.0 No repository field.
grunt@1.0.3
added 96 packages from 61 contributors and audited 179 packages in 117.365s
found 0 vulnerabilities
(Found node_modules folder created in site root)
5. Type in: grunt or grunt --help

#### RESULT: 
bash: grunt: command not found

#### EXPECTED RESULT: 
Run tasks

Operating System: Win7 64b

**Comment by GreggFranklin** [comment]
Issue resolved
