### ISSUE TITLE
Error with $ curl https://wordpress.org/latest.zip

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#21]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b3, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in:  curl https://wordpress.org/latest.zip

#### RESULT: 
curl: (77) error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

#### EXPECTED RESULT: 
Run tasks

Operating System: Win7 64b

**Comment by Steveorevo** [comment]
SSL certificate fixed in latest beta build 4. The complete command (process redirects, save as file with source name) should be:
```
curl https://wordpress.org/latest.zip -O -J -L
```

**Comment by erinmarinas** [comment]
Fixed. Works as expected.
