### ISSUE TITLE
Error with $ node-sass -v

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#22]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b3, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in: node-sass -v

#### RESULT: 
bash: node-sass: command not found

#### EXPECTED RESULT: 
Run tasks

Operating System: Win7 64b

**Comment by GreggFranklin** [comment]
node-sass will not be included in ds-cli. Closing
