### ISSUE TITLE
Error with $ git clone https://github.com/serverpress/bypass-login

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#23]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b3, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in: git clone https://github.com/serverpress/bypass-login

#### RESULT: 
Cloning into 'bypass-login'...
fatal: unable to access 'https://github.com/serverpress/bypass-login/': error setting certificate verify locations:
  CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none

#### EXPECTED RESULT: 
Run tasks

Operating System: Win7 64b

**Comment by Steveorevo** [comment]
certs fixed in beta 3 release

**Comment by erinmarinas** [comment]
Tested v3 beta4:

$ git clone https://github.com/serverpress/bypass-login
Cloning into 'bypass-login'...
Username for 'https://github.com': **[no text appears while typing]**
Password for 'https://erinmarinas@github.com': **[no text appears while typing]**
remote: Repository not found.
fatal: repository 'https://github.com/serverpress/bypass-login/' not found

**Comment by AkiraJinjuriki** [comment]
Download serverpress/bypass-login/ "bypass-login" ?

**Comment by GreggFranklin** [comment]
Resolved
