### ISSUE TITLE
"wp shell" error?

### ISSUE THREAD

**Issue by erinmarinas** [ServerPress/ds-cli#24]
#### STEPS TO REPRODUCE: 
1. Download 3.0.0b3, unzip and place in ds-plugins folder
2. Go to http://localhost and clicked on link for ds-cli
3. Type in: wp shell

#### RESULT: 
The system cannot find the path specified.

#### EXPECTED RESULT: 
Run and complete task.

Operating System: Win7 64b

**Comment by Steveorevo** [comment]
Note to self; This issue may be occurring because of missing components. Will try the following to correct the issue in next build. https://wordpress.stackexchange.com/questions/244001/wp-cli-shell-not-working-on-windows

**Comment by GreggFranklin** [comment]
This issue still exists
