### ISSUE TITLE
Move DS-CLI link from under the domains on the localhost page to a button

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/ds-cli#27]
In prepend_1

Change the action from 'list_domain' to 'domain_button_group'

`$ds_runtime->add_action( 'domain_button_group', 'ds_cli_list_domain_link' );
function ds_cli_list_domain_link( $domain ) {
	echo '<a href="http://localhost/ds-plugins/ds-cli/ds-launch-cli.php" data-domain="'.$domain.'" class="btn btn-info">DS CLI</a>';
}`

Remove:
`echo '<div class="ds-site-actions-container">';
echo '<a href="http://localhost/ds-plugins/ds-cli/ds-launch-cli.php" data-domain="'.$domain.'" class="ds-cli ds-action">DS CLI</a>';
echo '</div>';`

Add:
`echo '<a href="http://localhost/ds-plugins/ds-cli/ds-launch-cli.php" data-domain="'.$domain.'" class="btn btn-info">DS CLI</a>';`

![image 7](https://user-images.githubusercontent.com/1041421/51568110-cd77b400-1e4d-11e9-9404-d1891f535338.jpg)

**Comment by GreggFranklin** [comment]
Just noticed a terminal window is to opened after this change. Please review, not sure why.

**Comment by davejesch** [comment]
implemented.

"window is to opened" - do you mean "window is **not** opened"? I fixed this by adjusting the class name used in the javascript.

**Comment by GreggFranklin** [comment]
Implemented
