### ISSUE TITLE
Media edit of images in WordPress 4.6 shows broken link with DS-CLI enabled

### ISSUE THREAD

**Issue by Steveorevo** [ServerPress/ds-cli#4]
#### STEPS TO REPRODUCE:
1. Update or create a new website using WordPress 4.6
2. Ensure the DS-CLI plugin is enabled via DesktopServer's first option to "Stop or restart..." 
3. Import a new image in the Media Library and click edit to rotate the image.
#### RESULT:
1.  A broken link to the media appears.

Browser:  Safari
Browser Version: 9.1.1 
Operating System: Mac OS 10.11.5

![screen shot 2016-08-22 at 9 48 54 am](https://cloud.githubusercontent.com/assets/635399/17863225/bb3a5d82-684d-11e6-9c5a-abc20f00c3aa.png)
#### Workaround
1. Turn off DS-CLI via DesktopServer's first option to "Stop or restart..." 

We'll investigate the issue of a permanent fix.

**Comment by FrontPaw-Dev** [comment]
I have been troubleshooting this issue for two days.. I wanted to report the same issue is happening  to me as well and once I disabled the DS-CLI it fixed it. I wanted to let you know that it isn't isolated. 

I'm using Chrome.

**Comment by GreggFranklin** [comment]
Issue is resolved.
