### ISSUE TITLE
Output being generated interferes with XML content in AJAX calls

### ISSUE THREAD

**Issue by davejesch** [ServerPress/ds-cli#7]
Customer reported issue:
#### STEPS TO REPRODUCE:
1. Enable DS-CLI plugin when starting DS
2. Go to Posts -&gt; Categories
3. Turn on Google Inspector and go to the Network tab.
4. Enter information for a new category and click on the "Add New Category" button.
#### RESULT:

Page behaves as if the button was not clicked. The new category does not load and there is no error message displayed. Refreshing the page shows the newly added category on the right side of the page. If DS-CLI is not activated on startup the page behaves normally.
#### EXPECTED RESULT:

The page needs to be updated with the newly added category information

If you view the Results tab of the AJAX call to add the category, you notice that an extra blank line appears above the opening &lt;?xml tag. This results in Javascript being unable to interpret the response as valid XML.

I searched through the code, looking for extra whitespace after closing PHP tags and found nothing. I also tried forcing a "headers already sent" error which sometimes indicates the line of code that started output; also found nothing.

You can also see an extra blank line at the top of normal front-end pages, so somewhere output is being sent to the browser but right now I can't tell from where. So it's not just AJAX calls, it appears to be everything, but this is causing some XML based AJAX calls to break.

Browser:  any
Browser Version:  any
Operating System: any

**Comment by GreggFranklin** [comment]
This issue is resolved.
