### ISSUE TITLE
Whitespace being output during execution

### ISSUE THREAD

**Issue by davejesch** [ServerPress/ds-cli#8]
#### STEPS TO REPRODUCE: 
1. Activate DS-CLI
2. Use Google Inspector and go to the Networking tab
3. Perform actions involving API calls (specifically, using WPSiteSync for Genesis and Pull feature).
4. Examine the adminajax.php request in the Inspector and look at the Response

#### RESULT: 
Extra whitespace is added to the output when performing API calls. The JSON data returned by the 'pullgenesis' API in particular has additional whitespace before the JSON encoded structure.

This may also be causing issues when using Blueprints, but we haven't narrowed that down yet.

#### EXPECTED RESULT: 
No extra whitespace. The response should start with a '{' and end with a '}'

So far, I've seen three files that have closing PHP tags and might be causing the issue:
   ds-cli/vendor/composer/composer/tests/Composer/Test/Autoload/Fixtures/template/template_2.php
   ds-cli/vendor/wp-cli/php-cli-tools/http-console.php
   ds-cli/vendor/wp-cli/php-cli-tools/lib/cli/Shell.php

More likely, this is the result of one of the filters used in HTTP communications since this is happening (or at least more noticeable) when HTTP GET and POST operations are performed.

Browser:  n/a
Browser Version:  n/a
Operating System: Win/Mac

**Comment by jennifercloake** [comment]
Moving to ServerPress Bot.  Investigate when we have time.

**Comment by GreggFranklin** [comment]
Erin tested and no white space seen,
